version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ${DATABASE_PATH}:/app/${DATABASE_PATH}
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_PATH=${DATABASE_PATH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
    ports:
      - "${WEBHOOK_PORT}:8443"
      - "${PROBE_PORT}:8080"
    restart: always