version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./messages.db:/app/messages.db
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: always