version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ${DATABASE_PATH}:/app/${DATABASE_PATH}
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_PATH=${DATABASE_PATH}
      - PORT=${PORT}
    ports:
      - "${PORT}:8080"
    restart: always